### ISSUE TITLE
Pa_OpenStream the 2nd device return paDeviceUnavailable（-9985）on ASIO Driver 

### ISSUE THREAD

**Issue by David-He** [PortAudio/portaudio#557] opened 2021-04-20 04:16 UTC
(Please use the mailing list for support requests and general discussion. This is only for actual bugs.)

**Describe the bug**
Pa_OpenStream the 2nd device return paDeviceUnavailable（-9985）on ASIO Driver 

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1. There are 2 ASIO device.One is ASIO4All, the other is a real sound card supported with ASIO.
2. the code like this
PaStreamParameters inputParameters;
inputParameters.device = m_nPaDeviceIndex;
inputParameters.channelCount = PaInputDevice->maxInputChannels;//完全采集
inputParameters.sampleFormat = paInt16;
inputParameters.suggestedLatency = PaInputDevice->defaultLowInputLatency;
inputParameters.hostApiSpecificStreamInfo = NULL;

PaError err = Pa_OpenStream(&m_PaStream, &inputParameters, NULL, 48000, FRAMES_PER_BUFFER, paClipOff, recordCallback, this);
3. when I call the code in for loop. The 2nd time always return  -9985. No matter who is second .

**Expected behavior**
I think both cards should return pa_paNoError when call pa_OpenStream.

**Desktop (please complete the following information):**
 - OS: win10
 - OS Version 20H2
 - PortAudio version: pa_stable_v190600_20161030  asiosdk_2.3.3_2019-06-14
 - Windows ASIO

**Comment by philburk** [comment] 2021-04-25 17:34
I notice that you are using the 19.6.0 version from 2016. There have been a lot of changes since then and this problem may have already been fixed.

Can you please try with the new 19.7.0 release?
http://files.portaudio.com/download.html

**Comment by David-He** [comment] 2021-04-28 03:52
Thanks

> @David-He - I notice that you are using the 19.6.0 version from 2016. There have been a lot of changes since then and this problem may have already been fixed.
> 
> Can you please try with the new 19.7.0 release?
> http://files.portaudio.com/download.html

Thanks, @philburk I will download and try it.

**Comment by RossBencina** [comment] 2021-05-06 01:06
This is not a bug, it is as designed. It is a known issue due to limitations of the ASIO SDK - it only allows one driver to be open at a time. In principle this could be worked around by bypassing some large part of the ASIO SDK.

**Comment by RossBencina** [comment] 2022-03-03 02:07
Known issue. Duplicate of #76

**Closed by RossBencina** 2022-03-03 02:07 UTC
Labels: src-asio
