### ISSUE TITLE
GetStreamTime returns 0.0 for ALSA

### ISSUE THREAD

**Issue by Psirus** [PortAudio/portaudio#498] opened 2021-02-09 18:17 UTC
**Describe the bug**
I'm calling `Pa_GetStreamTime` while the stream is running, and expected an output != 0.0. This is not the case for me.

**To Reproduce**
1. I've added this simple code in the sine example to reproduce it:
~~~c
*** paex_sine.c	2021-02-09 19:01:57.772849115 +0100
--- paex_sine_mod.c	2021-02-09 18:56:38.971003126 +0100
*************** int main(void)
*** 154,160 ****
      if( err != paNoError ) goto error;
  
      printf("Play for %d seconds.\n", NUM_SECONDS );
!     Pa_Sleep( NUM_SECONDS * 1000 );
  
      err = Pa_StopStream( stream );
      if( err != paNoError ) goto error;
--- 154,163 ----
      if( err != paNoError ) goto error;
  
      printf("Play for %d seconds.\n", NUM_SECONDS );
!     Pa_Sleep( 2 * 1000 );
!     double time = Pa_GetStreamTime(stream);
!     printf("Stream time: %f\n", time );
!     Pa_Sleep( 2 * 1000 );
  
      err = Pa_StopStream( stream );
      if( err != paNoError ) goto error;
~~~
2. Compile with `gcc -O2 paex_sine_mod.c -lportaudio -lm`
3. Run `./a.out`
4. Output includes `Stream time: 0.000000`

**Expected behavior**
I expected it to print in the order of ~2.0. At least something nonzero.

**Actual behavior**
The `time` variable is 0.0. That could be because of an error (the documentation says *"The stream's current time in seconds, or 0 if an error occurred."*), but there is no indication of what that might be.

**Desktop:**
 - OS: Ubuntu
 - OS Version: 20.04
 - PortAudio version: 19.6.0 from the Ubuntu repos
 - Host API: ALSA

**Comment by RossBencina** [comment] 2022-03-17 01:41
Related (or possible duplicate?): #586

**Comment by RossBencina** [comment] 2022-03-24 00:38
Are you using PulseAudio or a native ALSA device?

**Comment by Psirus** [comment] 2022-03-25 14:06
Pulseaudio, I think. Debian Stable (bullseye) using Gnome.

**Comment by RossBencina** [comment] 2022-03-29 00:11
If it's PulseAudio then this is a duplicate of #586. Closing.

**Closed by RossBencina** 2022-03-29 00:11 UTC
Labels: bug, src-alsa, P3
