### ISSUE TITLE
Error -9996 when opening microphone in Qt application WASAPI

### ISSUE THREAD

**Issue by michael-hartmann** [PortAudio/portaudio#607] opened 2021-06-24 15:34 UTC
**Describe the bug**
When I try to open a microphone using portaudio Pa_OpenStream returns -9996 (invalid device). Portaudio is running on Windows 10 and using WASAPI as backend in exclusive mode. The code (portaudio and additional logic aroung it) is compiled as a DLL which is used inside a Qt application. When the very same DLL is used outside the Qt environment opening the microphone using Pa_OpenStream on the very same PC works.
To make things even stranger: One PC with Windows 10H2 works, the problematic PC is a Windows 10 version 1903.

As the microphone can be opened with the exact same DLL the problem cannot due to rights. Are there potential side-effects between portaudio and Qt? Do I have to take special care about threads?

I understand that this problem is basically impossible for you to debug. I'd be very happy about some pointers, though: In which file of the WASAPI backend is the -9996 error returned? Do you have any ideas how to debug this issue?

**Expected behavior**
I'd expect Pa_OpenStream to succeed no matter if the DLL is used by a Qt application or another application.

**Actual behavior**
Pa_OpenStream returns -9996.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version 1903 (another PC with Windows 20H2 works fine)
 - PortAudio version: pa_stable_v190700_20210406.tgz
 - WASAPI in exclusive mode

**Additional context**

**Comment by dmitrykos** [comment] 2021-06-24 20:22
paInvalidDevice maybe thrown if WASAPI interface could not be instantiated, e.g. OS did not allow to do that. If the same DLL works fine for different apps then please check the permission for the Qt application, for one app permission to access microphone could be allowed and for another app not.

**Comment by michael-hartmann** [comment] 2021-06-25 09:04
It turns out that portaudio fails because apparently "CoInitialize" has not been called. I will take a closer look, but it's most likely not a portaudio problem.

**Comment by dechamps** [comment] 2021-06-25 09:15
I don't remember the exact details, but I hit a similar problem with CoInitialize. The problem is that WASAPI calls, being COM calls, only work in threads where CoInitialize have been called. IIRC, the PortAudio WASAPI code doesn't call CoInitialize in every entry point before calling WASAPI functions. This can lead to very subtle issues where PortAudio WASAPI code can fail if it happens to be called from more than one user thread (even if the calls are properly serialized!).

Assuming I'm correct, I think this should be treated as a bug in PortAudio. The PortAudio caller shouldn't know, and shouldn't care, that CoInitialize is a thing - that's an implementation detail of the WASAPI Host API. I suspect the proper fix is for the PortAudio WASAPI code to always call CoInitialize in every entry point that uses WASAPI functions.

**Comment by michael-hartmann** [comment] 2021-06-25 09:17
Would it help it call CoInitialize manually before calling any portaudio functions?

**Comment by dechamps** [comment] 2021-06-25 09:46
Yes, that's how I originally worked around this problem. But my point is, we should fix PortAudio so that you don't have to do that.

**Comment by michael-hartmann** [comment] 2021-06-25 10:01
@dechamps: I agree, ideally portaudio takes care of it and I don't have to care as a user.

**Comment by dmitrykos** [comment] 2021-06-25 19:21
In case of WASAPI `CoInitialize` is called inside the internal processing threads as well as in `PaWasapi_Initialize`. 

So if you adjust your software design to the way when only one thread is calling PortAudio API then there won't be any issue. It will also eliminate any potential race conditions. 

To my view it is a good practice and the most reliable way.

Adding `CoInitialize` for an every external call (and let's do not forget that we need to clean it up with `CoUninitialize`) looks like a workaround for a sub-optimal software design rather than a bug-fix of the current implementation. 

Imagine if application is starting a new thread for an every call to PA interface and we call `CoInitialize` because a new thread Id is detected. In this case we do not control the life-time of the user thread and do not know if it exited in order to call ``CoUninitialize` to release memory. As a result there will be a constant memory leak that has a potential to break the process once all memory is consumed. So it is better to fail on unserialized usage of the API immediately and re-design application to fix that rather then to debug a constant memory leak.

**Comment by dechamps** [comment] 2021-06-25 19:28
@dmitrykos Your concern with leaks is a non-issue. `CoInitialize` is [designed](https://docs.microsoft.com/en-us/windows/win32/api/objbase/nf-objbase-coinitialize) such that additional Initialize/Uninitialize calls are benign and won't do anything as long as they are balanced:

> Subsequent calls to CoInitialize or CoInitializeEx on the same thread will succeed, as long as they do not attempt to change the concurrency model, but will return S_FALSE. To close the COM library gracefully, each successful call to CoInitialize or CoInitializeEx, including those that return S_FALSE, must be balanced by a corresponding call to CoUninitialize.

> if you adjust your software design to the way when only one thread is calling PortAudio API

Do you really want to make that part of the documented PortAudio API contract? It's an awkward requirement that will surprise users. Users don't typically expect a library to care which thread it's being called on (as long as the calls are serialized, of course). It's also unnecessary. PortAudio could simply do a `CoInitialize`/`CoUnnitialize` pair on every entry point, which is basically free and will ensure the PortAudio functions work no matter which thread they are being called from.

**Comment by dmitrykos** [comment] 2021-06-25 19:34
@dechamps I am not talking about calling `CoInitialize` multiple times inside the same thread, I provided a completely different scenario which has no good workaround from the side of PortAudio (with it current public API).

I quote myself again:
> **Imagine if application is starting a new thread for an every call to PA interface and we call `CoInitialize` because a new thread Id is detected**. In this case we do not control the life-time of the user thread and do not know if it exited in order to call `CoUninitialize` to release memory. As a result there will be a constant memory leak that has a potential to break the process once all memory is consumed. So it is better to fail on unserialized usage of the API immediately and re-design application to fix that rather then to debug a constant memory leak which happens after several hours of app operation.

**Comment by dechamps** [comment] 2021-06-25 19:45
I don't follow.

All I'm saying is: every PortAudio WASAPI function should call `CoInitialize` on entry, and `CoUninitialize` on exit. I don't understand what you mean by "a new thread ID is detected" - we don't need to "detect new threads", we can just call these (un)init functions unconditionally, period.

Like, literally something like this:

```c++
static PaError StartStream( PaStream *s ) {
  CoInitialize();
  …
  CoUninitialize();
}
```

That's it. And so on and so forth for every public entry point in `pa_win_wasapi.c`. I don't understand why you are worried about "leaks" with this approach - every function call cleans up after itself, always. In the above example, leaks are impossible by construction (as long as all return statements are so covered, of course).

So to take your example, "if application is starting a new thread for an every call to PA interface", then PortAudio will initialize COM in each new thread when it's called and then immediately deinitialize it in the same thread as soon as the PortAudio function call ends. Which is perfectly fine and is exactly the way COM is supposed to work.

> it is better to fail on unserialized usage

Serialization and multi-threading are not the same thing. You can call a library serially from multiple threads, and users will typically expect a library to support that use case unless officially documented otherwise, even if the library is documented as thread-unsafe.

**Comment by dmitrykos** [comment] 2021-06-25 20:32
@dechamps your argumentation does not convince me I am afraid. Your proposal is not suitable for a blocking API of PortAudio, e.g. `Pa_WriteStream/Pa_ReadStream` for example. We can not call `CoInitialize` and `CoUninitialize` inside the tight loop all the time, I hope it is pretty clear that we get an overhead of unknown impact in case user is calling it from an `unauthorized thread`.

That is why I did not assume the approach your proposed in my previous reply.

The only feasible workaround which would work for a blocking API too can be a detection of the calling thread Id and doing `CoInitialize`. But deficiency of this approach is that we need an additional API (function) which user has to call on thread exit from inside the exiting thread, so we would call `CoUninitialize`. It complicates things and exposes PortAudio to be a memory leaker if that API is not called, so I will repeat - the best and most reliable approach is to serialize all API calls to PortAudio and do them from a single (maybe dedicated) thread.

**Comment by RossBencina** [comment] 2021-07-01 00:58
I haven't read this whole discussion but as a general rule, PA uses a single threaded model. You should call Pa_Initialize and all other functions from the same thread. My understanding is that there is no issue with PA/WASAPI if you use PortAudio like this.

If you want to use the PA API from multiple threads you need to deal with issues yourself. One issue would be making sure that COM is initialized -- you probably need to do this for PA/DirectSound too. Another issue is that you need to ensure that PA is called from only one thread at a time by wrapping all API calls in a mutex.

Related: #254

**Comment by dmitrykos** [comment] 2021-07-01 06:58
@RossBencina you are right, PA WASAPI has to be used either from a single thread which also called `Pa_Initialize` or otherwise user has to make sure to call Windows system API `CoInitialize` in each user-side thread which is trying to call any PA function because the thread life-time is unknown to PA internals.

PA WASAPI is calling  `CoInitialize` during the initialization stage, so single thread access is perfectly supported and valid:
https://github.com/PortAudio/portaudio/blob/16884fc2019cd8b269eac000db9e2bd938f89a85/src/hostapi/wasapi/pa_win_wasapi.c#L2338

Closing #607 issue.

**Closed by dmitrykos** 2021-07-01 06:58 UTC
Labels: src-wasapi

**Comment by michael-hartmann** [comment] 2021-07-04 14:54
I understand your reasoning for closing this issue.

When I stumbled over this problem I also tried to find some information about using portaudio from multiple threads but couldn‘t find any. I guess that the behavior will differ depending on the backend. My expectation was that it should be safe to call portaudio functions from different threads as long the calls are not happening concurrently. Evidently my expectation wasn‘t right.

It would be helpful to have documentation that states if and under what conditions portaudio functions can be called from different threads.
