### ISSUE TITLE
Creating a `portaudio::AutoSystem` changes the locale

### ISSUE THREAD

**Issue by bhennion** [PortAudio/portaudio#661] opened 2021-11-10 12:15 UTC
**Describe the bug**
When a `portaudio::AutoSystem` is instanciated and a global C locale is set, the C locale gets reset to `"C"`. The C++ locale is unchanged.

**To Reproduce**
Here is a MWE:
```
#include <portaudiocpp/PortAudioCpp.hxx>

int main(int argc, char *argv[])
{
    std::locale loc;
    printf("*** C++ locale is %s\n", loc.name().c_str());
    printf("*** C locale is %s\n", setlocale(LC_NUMERIC, NULL));
    printf("*** printf prints: %f\n", 12345.6789);
    
    printf("*** Setting locale\n");
    std::locale::global(std::locale(""));
    std::locale loc2;
    printf("*** C++ locale is %s\n", loc2.name().c_str());
    printf("*** C locale is %s\n", setlocale(LC_NUMERIC, NULL));
    printf("*** printf prints: %f\n", 12345.6789);
    
    printf("*** Calling `portaudio::AutoSystem autoSys;`\n\n");
    portaudio::AutoSystem autoSys;
    std::locale newloc;
    printf("\n*** C++ locale is %s\n", newloc.name().c_str());
    printf("*** C locale is %s\n", setlocale(LC_NUMERIC, NULL));
    printf("*** printf prints %f\n", 12345.6789);

    return 0;
}
```
to be compiled with 
```
g++ -o mwe portaudio-mwe.cpp `pkg-config --cflags --libs portaudiocpp`
```

The ouput I get:
```$ ./mwe 
*** C++ locale is C
*** C locale is C
*** printf prints: 12345.678900
*** Setting locale
*** C++ locale is fr_FR.UTF-8
*** C locale is fr_FR.UTF-8
*** printf prints: 12345,678900
*** Calling `portaudio::AutoSystem autoSys;`

ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

*** C++ locale is fr_FR.UTF-8
*** C locale is C
*** printf prints 12345.678900
```

**Expected behavior**
Portaudio should not be changing the global locale.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - PortAudio version: Tried 19.6.0, 19.7.0 and latest `master`

**Additional context**
This causes a bug in Xournal++, see the downstream [bug report](https://github.com/xournalpp/xournalpp/issues/3388), where a string is written using the C++ locale (as it should be in a C++ program), but parsed by a `sscanf` by a library written in C (here `cairo`).

**Comment by RossBencina** [comment] 2021-11-12 01:31
As far as I can tell this could be an issue with portaudio rather than the C++ wrapper. the System class doesn't do anything special:

https://github.com/PortAudio/portaudio/blob/master/bindings/cpp/source/portaudiocpp/System.cxx

Would it be possible to run your test with a call directly to `Pa_Initialize()` (#include "portaudio.h") rather than instantiating `portaudio::AutoSystem` please?

**Comment by bhennion** [comment] 2021-11-12 04:42
Of course! It gives me the same thing indeed:
```
*** C++ locale is C
*** C locale is C
*** printf prints: 12345.678900
*** Setting locale
*** C++ locale is fr_FR.UTF-8
*** C locale is fr_FR.UTF-8
*** printf prints: 12345,678900
*** Calling `Pa_Initialize();`

ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

*** C++ locale is fr_FR.UTF-8
*** C locale is C
*** printf prints 12345.678900
```

**Comment by Photon89** [comment] 2021-11-13 11:51
Possibly the following debugging information is helpful: https://gitlab.freedesktop.org/cairo/cairo/-/issues/523#note_1156857 Looks like LC_NUMERIC differs from other LC_xxx variables.

**Comment by philburk** [comment] 2021-11-14 22:35
It appears ALSA is changing the locale so it can use strtod() to parse a double from a string. Maybe it is not changing it back properly. 

https://git.alsa-project.org/?p=alsa-lib.git;a=blob;f=src/conf.c;h=0c3cc736e7c956e55000ed58e8d1539b99e0e5be;hb=HEAD#l721

https://alsa-devel.alsa-project.narkive.com/IxnbRi85/patch-alsa-lib-2-2-use-thread-safe-locale-functions-if-available

**Comment by bhennion** [comment] 2021-11-15 07:09
@philburk Thanks for the hint!
Would there be a test I can run to make sure that ALSA is the culprit here?

**Comment by philburk** [comment] 2021-11-18 01:52
@bhennion - Try building PortAudio with just PA_USE_OSS and not PA_USE_ALSA and see if it changes the locale.
Then add PA_USE_ALSA and see what happens.

**Comment by bhennion** [comment] 2021-11-18 18:15
Indeed, building with
```
./configure --without-alsa
make
```
removes the bug. Here is the output of my MWE from a couple of posts above:
```
*** C++ locale is C
*** C locale is C
*** printf prints: 12345.678900
*** Setting locale
*** C++ locale is fr_FR.UTF-8
*** C locale is fr_FR.UTF-8
*** printf prints: 12345,678900
*** Calling `Pa_Initialize();`

Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

*** C++ locale is fr_FR.UTF-8
*** C locale is fr_FR.UTF-8
*** printf prints 12345,678900
```
Note that in the end, it does not seem to be doing a lot either, and no streams are found anymore in the downstream app (Xournal++).

Still this seems to be pointing towards an ALSA problem. Would you help me forwarding the issue upstream? I really don't know how ALSA is used in PA, so I don't know how to make an efficient bug report.

**Comment by philburk** [comment] 2021-11-21 01:20
PortAudio just calls ALSA when run on Linux. We have no special relationship with ALSA.

I recommend filing a bug on the ALSA issues page.

https://github.com/alsa-project/alsa-lib/issues

Link to this bug but also include a summary and why you think the problem is in ALSA. Link to the code in conf.c.

**Comment by philburk** [comment] 2021-12-02 01:46
Closing because the fix is needed in ALSA. Not our bug.

**Closed by philburk** 2021-12-02 01:46 UTC
