### ISSUE TITLE
Invalid max output channel count reported using WASAPI causing channel mismatch error when (count > 2) (see ALSA #353)

### ISSUE THREAD

**Issue by 92es** [PortAudio/portaudio#365] opened 2020-12-16 19:46 UTC
**Describe the bug**

Port Audio appears to be returning the wrong max output channel count when using WASAPI EXCLUSIVE.  It appears to be erroneously defaulting to 2 channel stereo for WASAPI EXCLUSIVE, but returns the proper max channel count of 8 when using MME, Direct Sound and Kernel Streaming.  **This causes a “channel count mismatch error” which is handled inconsistently among associated software using Port Auido.  Some software errors out and does not work, others work around the bug.**

This appears to be similar to the Linux/ALSA's bug report #353, but with Windows/WASAPI EXCLUSIVE.

**To Reproduce**

This happens when using a Lynx HiLo and a OKTO Research DAC8 PRO (and may happen with other multi-channel audio devices).

JRiver Media Center’s WMD driver also sees the incorrect max channel count of 2 using WASAPI EXCLUSIVE, but the correct count of 8 for MME and Direct Sound.

This happens consistently on Windows 7-64 Ultimate running FlexASIO or Audiolense.

The log below is from FlexASIO/Port Audio WASAPI EXCLUSIVE showing the JRMC’s WMD Driver (device index 10) and a Theyscon USB DAC Driver (device index 11), both in error, yet the other non-WASAPI variants are returning the proper max output channel count of 8.

**Actual behavior**

PA device index 1 (name: 'Microphone (Umik-1  Gain: 18dB ', host API: 0, default sample rate: 44100, max input channels: 2, max output channels: 0, input latency: 0.09 (low) 0.18 (high), output latency: 0.09 (low) 0.18 (high))
PA device index 2 (name: 'Microsoft Sound Mapper - Output', host API: 0, default sample rate: 44100, max input channels: 0, max output channels: 2, input latency: 0.09 (low) 0.18 (high), output latency: 0.09 (low) 0.18 (high))
PA device index 3 (name: 'JRiver Media Center 25 (JRiver ', host API: 0, default sample rate: 44100, max input channels: 0, **max output channels: 8**, input latency: 0.09 (low) 0.18 (high), output latency: 0.09 (low) 0.18 (high))
PA device index 4 (name: 'Speakers (DIYINHK USB Audio)', host API: 0, default sample rate: 44100, max input channels: 0, **max output channels: 8**, input latency: 0.09 (low) 0.18 (high), output latency: 0.09 (low) 0.18 (high))
PA device index 5 (name: 'Primary Sound Capture Driver', host API: 1, default sample rate: 44100, max input channels: 2, max output channels: 0, input latency: 0.12 (low) 0.24 (high), output latency: 0 (low) 0 (high))
PA device index 6 (name: 'Microphone (Umik-1  Gain: 18dB  )', host API: 1, default sample rate: 44100, max input channels: 2, max output channels: 0, input latency: 0.12 (low) 0.24 (high), output latency: 0 (low) 0 (high))
PA device index 7 (name: 'Primary Sound Driver', host API: 1, default sample rate: 44100, max input channels: 0, max output channels: 2, input latency: 0 (low) 0 (high), output latency: 0.12 (low) 0.24 (high))
PA device index 8 (name: 'JRiver Media Center 25 (JRiver Media Center 25)', host API: 1, default sample rate: 44100, max input channels: 0, **max output channels: 8**, input latency: 0 (low) 0 (high), output latency: 0.12 (low) 0.24 (high))
PA device index 9 (name: 'Speakers (DIYINHK USB Audio)', host API: 1, default sample rate: 44100, max input channels: 0, **max output channels: 8**, input latency: 0 (low) 0 (high), output latency: 0.12 (low) 0.24 (high))

**>>>>>> ERROR: WASAPI EXCLUSIVE (Host API 2) incorrectly reporting the 8 max channel count as 2.**

PA device index 10 (name: 'Speakers (DIYINHK USB Audio)', host API: 2, default sample rate: 48000, max input channels: 0, **max output channels: 2**, input latency: 0 (low) 0 (high), output latency: 0.003 (low) 0.01 (high))
PA device index 11 (name: 'JRiver Media Center 25 (JRiver Media Center 25)', host API: 2, default sample rate: 48000, max input channels: 0, **max output channels: 2**, input latency: 0 (low) 0 (high), output latency: 0.003 (low) 0.01 (high))

**ERROR <<<<<<**

PA device index 12 (name: 'Microphone (Umik-1  Gain: 18dB  )', host API: 2, default sample rate: 48000, max input channels: 2, max output channels: 0, input latency: 0.003 (low) 0.01 (high), output latency: 0 (low) 0 (high))
PA device index 13 (name: 'Output (JRVAD Wave)', host API: 3, default sample rate: 44100, max input channels: 0, **max output channels: 8**, input latency: 0.01 (low) 0.0853333 (high), output latency: 0.01 (low) 0.0853333 (high))
PA device index 14 (name: 'Line (DAC8PRO)', host API: 3, default sample rate: 44100, max input channels: 8, max output channels: 0, input latency: 0.01 (low) 0.0853333 (high), output latency: 0.01 (low) 0.0853333 (high))
PA device index 15 (name: 'Speakers (DAC8PRO)', host API: 3, default sample rate: 44100, max input channels: 0, **max output channels: 8,** input latency: 0.01 (low) 0.0853333 (high), output latency: 0.01 (low) 0.0853333 (high))
PA device index 16 (name: 'Microphone (Umik-1  Gain: 18dB)', host API: 3, default sample rate: 48000, max input channels: 2, max output channels: 0, input latency: 0.01 (low) 0.0853333 (high), output latency: 0.01 (low) 0.0853333 (high))

**Desktop (please complete the following information):**

Windows 7-64 Bit Ultimate
Audiolense XO - 64 bit Demo App 6.12
FlexASIO 1.6 - 64 bit

**Comment by dmitrykos** [comment] 2020-12-16 20:20
Would you please clarify:

1. What mode is selected for WASAPI: Shared or Exclusive
2. What channel configuration is set in the OS's Sound CPL

**Comment by 92es** [comment] 2020-12-16 22:10
WASAPI EXCLUSIVE 
8 Channels
The OKTO DAC8 PRO has USB Stereo 2 channels, 8 AES3 digital inputs and 8 AES/XLR analog outputs.

**Comment by dechamps** [comment] 2020-12-16 22:35
Hello, [FlexASIO](https://github.com/dechamps/FlexASIO) developer here.

> Would you please clarify:
>     1. What mode is selected for WASAPI: Shared or Exclusive

That doesn't matter here, the FlexASIO log is merely listing what is being reported by `Pa_GetDeviceInfo()`. The stream isn't even opened yet. @92es is mistaken when they say that "WASAPI exclusive" is reporting 2 channels. It's the PortAudio device info for WASAPI *in general* that is reporting 2 channels.

>     2. What channel configuration is set in the OS's Sound CPL

Seconded.

> The OKTO DAC8 PRO has USB Stereo 2 channels, 8 AES3 digital inputs and 8 AES/XLR analog outputs.

@92es: That's not what @dmitrykos asked for. Please make sure that your channel count is correctly configured in the Windows audio control panel settings. We're referring to this specific page:

![image](https://user-images.githubusercontent.com/866859/102413660-30980400-3fed-11eb-8116-d3ad5ac41c24.png)

Your symptoms are highly consistent with this setting being misconfigured. I've seen cases where DirectSound and MME would still show 8 channels but that's only because they support downmixing.

Also, @92es, a word about the bug reporting process: you seem to be a FlexASIO user, not a PortAudio user (unless you are willing to discuss things from the perspective of a developer dealing with FlexASIO source code, but it doesn't look like that's your intent). As a FlexASIO user you are not using PortAudio directly and PortAudio developers cannot be expected to investigate the way FlexASIO uses PortAudio internally. As a result, having this discussion here is a bit awkward. It would have been more appropriate to report this as a [FlexASIO issue](https://github.com/dechamps/FlexASIO/issues), instead of coming directly to PortAudio. I can then liaise with PortAudio as appropriate.

**Comment by 92es** [comment] 2020-12-16 22:58
@ dechamps, It is also  happening in Audiolense XO 6.12 which directly uses PortAudio or FlexASIO.  I saw FlexASIO had a logging feature so I used it and saw the PortAudio messages as well as the FlexASIO messages in the logs.  Audiolense confirms they are seeing the same thing using PortAudio directly.

I have not looked at either code sets directly, just reporting the issue.

I will have to look up Windows CPL as I am not familiar with it and don't code in Windows.

**Comment by dechamps** [comment] 2020-12-16 23:11
@92es 

> I will have to look up Windows CPL

CPL just means "Control Panel". That's the screenshot you posted.

Another way to adjust the channel count is to right click on the audio device and click "Configure Speakers". You should end up with something like this:

![image](https://user-images.githubusercontent.com/866859/102417568-d6e70800-3ff3-11eb-86fc-98f0cf9457b8.png)

Please make sure the configuration is correct there.

**Comment by 92es** [comment] 2020-12-16 23:28
@dechamps , I just found and did that.  I set it to 7.1, but the following display stays the same if it is set to 2 or 7.1.

![DAC8Pro_Sound_Confirations](https://user-images.githubusercontent.com/76127081/102418041-d299fb00-3fb1-11eb-8963-d2f50e540c52.jpg)

I reran the FlexASIO logs and see the logs are reporting 8 output channels for the DIYINHK USB driver.  Audiolense XO still has a mismatch error using PortAudio directly.  I have not finished comparing the 2 logs, but FlexASIO is as functional as before.

2020-12-16T14:49:57.6711437-08:00 4840 4844 Found device: PortAudio device index 10 (name: 'Speakers (DIYINHK USB Audio)', **host API: 2**, default sample rate: 48000, max input channels: 0, **max output channels: 8,** input latency: 0 (low) 0 (high), output latency: 0.003 (low) 0.01 (high))
2020-12-16T14:49:57.6711437-08:00 4840 4844 Found device: PortAudio device index 11 (name: 'JRiver Media Center 25 (JRiver Media Center 25)', **host API: 2**, default sample rate: 48000, max input channels: 0, **max output channels: 2**, input latency: 0 (low) 0 (high), output latency: 0.003 (low) 0.01 (high))
2020-12-16T14:49:57.6711437-08:00 4840 4844 Found device: PortAudio device index 12 (name: 'Microphone (Umik-1  Gain: 18dB  )', **host API: 2**, default sample rate: 48000, max input channels: 2, max output channels: 0, input latency: 0.003 (low) 0.01 (high), output latency: 0 (low) 0 (high))

**Comment by dechamps** [comment] 2020-12-16 23:49
@92es

> the following display stays the same if it is set to 2 or 7.1

Yes, Windows makes the channel count configurable in that dialog or the other, but not both. It seems to depend on the specifics of the device. IIRC, configuring the channel count in the "Advanced" tab mostly applies to input (recording) devices only.

If I understand your last post correctly, the issue appears to be fixed in FlexASIO. This would seem to indicate that there is nothing that needs fixing in PortAudio. I filed dechamps/FlexASIO#102 to better document this behavior for FlexASIO users.

**Comment by 92es** [comment] 2020-12-17 00:19
@dechamps , FWIW, I never had to change the Windows Control Panel/Sound/Device/Configure option channel count  for MME, DirectSound or KS for them to report the proper channel count of 8, only WASAPI.   Something is NOT consistent among the 4 options with only 1 of the 4 requiring manual intervention.

It appears there is still an issue with AL XO 6.12 which continues to error out.  FlexASIO worked around the issue irrespective of the setting causing the channel mismatch.  The new FlexASIO logs with the setting of 8 do not show the channel number mismatch.

Thank you for your help.

**Comment by dechamps** [comment] 2020-12-17 00:56
> I never had to change the Windows Control Panel/Sound/Device/Configure option channel count for MME, DirectSound

Have you actually checked that all 8 channels worked and were properly routed when using MME or DirectSound in the previous state where the Windows audio device was misconfigured? I suspect the reason why they reported 8 channels all along is because of automatic downmixing. It could very well be that MME and DS report 8 channels, but when you actually try to use them you realize that you can only get stereo to work properly, and any additional channel gets downmixed implicitly.

I don't think Windows audio device settings matter as much in the specific case of WDM-KS because that particular backend has a more direct path to the hardware audio driver. It does not surprise me that the channel count reported by the PortAudio WDM-KS code is independent of these settings.

**Comment by 92es** [comment] 2020-12-17 01:23
I have avoided MME and DS to bypass as much of the Windows stack as possible, so no, I haven't tested them directly other than seeing the printouts.  I was having problems with the random clock drifts between a USB mic and a USB DAC so I decided to try WASAPI after using KS to see if it was any better.  I will probably have to get an ADC that can be slaved from the DAC's external clock to get past the clock drift issues I am having (besides the channel count issue).  I am trying to do digital XOs, frequency, phase and time domain FIR filters.

**Comment by dmitrykos** [comment] 2020-12-17 08:02
WASAPI, unlike MME or DirectSound, when in Shared mode is accepting the format specified in the Sound CPL, e.g.:
- channel count
- frequency

So it may be perceived as limitation but the goal of Microsoft (probably) was to avoid audio data conversions. Shared mode audio streams are getting into the internal OS mixer which mixes all shared streams into one and outputs to the hardware. So PA for WASAPI interface will report what is assigned in the Sound CPL otherwise stream can not be created due to format mismatch. 

To overcome this and to be able to use max supported channel count, exact sample type (bits) and any supported frequency, e.g.  to not depend on Sound CPL settings, the application (client) should use Exclusive mode which is activated by the `paWinWasapiExclusive` flag.

**Comment by dechamps** [comment] 2020-12-17 09:43
> To overcome this and to be able to use max supported channel count, exact sample type (bits) and any supported frequency, e.g. to not depend on Sound CPL settings, the application (client) should use Exclusive mode which is activated by the `paWinWasapiExclusive` flag.

Unless I missed something this won't actually work, because the PortAudio WASAPI code will immediately reject any `Pa_OpenStream()` call with a channel count higher than `PaDeviceInfo::maxOutputChannels`, even if `paWinWasapiExclusive` is passed: https://github.com/PortAudio/portaudio/blob/e76f8fdd40c59cc7185c866ebf9c37a5991a1ecd/src/hostapi/wasapi/pa_win_wasapi.c#L3043-L3044

**Comment by dmitrykos** [comment] 2020-12-17 10:19
@dechamps , you can query max supported channels with `Pa_IsFormatSupported` which accepts `PaStreamParameters` where you can pass the `paWinWasapiExclusive` flag. Then you open the stream with the format confirmed by the `Pa_IsFormatSupported`.

**Comment by dmitrykos** [comment] 2020-12-17 10:20
@dechamps , I will check that and comment.

**Comment by dmitrykos** [comment] 2020-12-17 10:29
@dechamps , you are correct. Thank you for noticing it and this issue needs to be rectified for the Exclusive mode for sure. I will come up soon with the PR for this issue and then let's check if it works fine for all.

**Comment by RossBencina** [comment] 2020-12-18 07:07
I would just like to point out that the premise of this issue is bogus. The user should not make any assumptions that independent host APIs will return the same number of channels for what it thinks are the same devices. I recommend closing this ticket as not-a-bug.

**Closed** 2020-12-18 07:33 UTC

**Comment by philburk** [comment] 2025-09-02 00:49
Here is a translation of the previous post:

Description error

Port Audio appears to be returning an incorrect maximum number of output channels when using WASAPI EXCLUSIVE. It appears to incorrectly default to 2-channel stereo for WASAPI EXCLUSIVE, but returns the correct maximum number of 8 channels when using MME, direct sound, and kernel streaming. This results in a "channel count mismatch error," which is handled inconsistently across software using Port Audio. Some software experiences errors and fails to work correctly, while others are able to work around the error.

https://github.com/PortAudio/portaudio/issues/353 for Linux/ALSA , but identical to Windows/WASAPI EXCLUSIVE.

Reappearance

This happens with the Lynx HiLo and the OKTO Research DAC8 PRO (it may also happen with other multi-channel audio devices).

JRiver Media Center's WMD driver also sees an incorrect maximum channel count of 2 with WASAPI EXCLUSIVE, but a correct count of 8 for MME and Direct Sound.

This happens consistently on Windows 7-64 Ultimate running FlexASIO or Audiolense.

The log below is from FlexASIO/Port Audio WASAPI EXCLUSIVE and shows that both JRMC's WMD driver (device index 10) and the Theyscon USB DAC driver (device index 11) fail, but the other non-WASAPI variants return the correct maximum output channels of 8.

Actual behavior

PA device index 1 (name: "Microphone (Umik-1 Gain: 18dB", Host API: 0, Default Sample Rate: 44100, Max Input Channels: 2, Max Output Channels: 0, Input Latency: 0.09 (Low) 0.18 (High), Output Latency: 0.09 (Low) 0.18 (High)) PA device index 2 (name: "Microsoft Sound Mapper - Output", Host API: 0, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 2, Input Latency: 0.09 (Low) 0.18 (High), Output Latency: 0.09 (Low) 0.18 (High)) PA device index 3 (name: "JRiver Media Center 25 (JRiver)," Host API: 0, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 8 , Input Latency: 0.09 (Low) 0.18 (High), Output Latency: 0.09 (Low) 0.18 (High)) PA device index 4 (Name: 'Speaker (DIYINHK USB Audio)', Host API: 0, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 8 , Input Latency: 0.09 (Low) 0.18 (High), Output Latency: 0.09 (Low) 0.18 (High)) PA device index 5 (Name: 'Main Sound Capture Driver', Host API: 1, Default Sample Rate: 44100, Max Input Channels: 2, Max Output Channels: 0, Input Latency: 0.12 (Low) 0.24 (High), Output Latency: 0 (Low) 0 (High)) PA device index 6 (Name: 'Microphone (Umik-1 Gain: 18dB)", Host API: 1, Default Sample Rate: 44100, Max Input Channels: 2, Max Output Channels: 0, Input Latency: 0.12 (Low) 0.24 (High), Output Latency: 0 (Low) 0 (High)) PA Device Index 7 (Name: "Main Sound Driver", Host API: 1, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 2, Input Latency: 0 (Low) 0 (High), Output Latency: 0.12 (Low) 0.24 (High)) PA Device Index 8 (Name: "JRiver Media Center 25 (JRiver Media Center 25)", Host API: 1, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 8 , Input Latency: 0 (Low) 0 (High), Output Latency: 0.12 (Low) 0.24 (High)) PA Device Index 9 (Name: "Speaker (DIYINHK USB Audio), Host API: 1, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 8 , Input Latency: 0 (Low) 0 (High), Output Latency: 0.12 (Low) 0.24 (High)

>>>>>> BUG: WASAPI Exclusive (Host API 2) incorrectly reports 8 maximum channel count as 2.

PA device index 10 (Name: "Speaker (DIYINHK USB Audio)", Host API: 2, Default Sample Rate: 48000, Maximum Input Channels: 0, Maximum Output Channels: 2 , Input Latency: 0 (Low) 0 (High), Output Latency: 0.003 (Low) 0.01 (High)) PA device index 11 (Name: "JRiver Media Center 25 (JRiver Media Center 25)", Host API: 2, Default Sample Rate: 48000, Maximum Input Channels: 0, Maximum Output Channels: 2 , Input Latency: 0 (Low) 0 (High), Output Latency: 0.003 (Low) 0.01 (High))

Error<<<<<<

PA device index 12 (Name: "Microphone (Umik-1 Gain: 18dB)", Host API: 2, Default Sample Rate: 48000, Max Input Channels: 2, Max Output Channels: 0, Input Latency: 0.003 (Low) 0.01 (High), Output Latency: 0 (Low) 0 (High)) PA device index 13 (Name: "Output (JRVAD Wave)", Host API: 3, Default Sample Rate: 44100, Max Input Channels: 0, Max Output Channels: 8 , Input Latency: 0.01 (Low) 0.0853333 (High), Output Latency: 0.01 (Low) 0.0853333 (High)) PA Device Index 14 (Name: 'Line (DAC8PRO)', Host API: 3, Default Sample Rate: 44100, Max Input Channels: 8, Max Output Channels: 0, Input Latency: 0.01 (Low) 0.0853333 (High), Output Latency: 0.01 (Low) 0.0853333 (High)) PA Device Index 15 (Name: 'Speaker (DAC8PRO)', Host API: 3. Default sample rate: 44100, Maximum number of input channels: 0, Maximum number of output channels: 8, Input delay: 0.01 (low) 0.0853333 (high), Output delay: 0.01 (low) 0.0853333 (high)) PA device index 16 (Name: "Microphone (Umik-1 Gain: 18dB)", Host API: 3, Default sample rate: 48000, Maximum number of input channels: 2, Maximum number of output channels: 0, Input delay: 0.01 (low) 0.0853333 (high), Output delay: 0.01 (low) 0.0853333 (high))

Desktop version (please fill in the following information):

Windows 7 - 64 bit Ultimate Audiolense XO - 64 bit Demo Application 6.12 FlexASIO 1.6 - 64 bit

**Comment by dmitrykos** [comment] 2025-09-02 07:00
@philburk you translated the initial post of this PR from @1213c which I assume is a bot :) I propose to delete that post to cleanup this thread.
