### ISSUE TITLE
PortAudio error while opening stream: Internal PortAudio error

### ISSUE THREAD

**Issue by mayankkuls** [PortAudio/portaudio#520] opened 2021-02-24 08:56 UTC
We are using Big Sur mac os and get this error

||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error
PortAudio error while opening stream: Internal PortAudio error
Segmentation fault: 11

**Comment by rryan** [comment] 2021-02-25 21:09
Error code 66748 is kAudioComponentErr_NotPermitted.

On Big Sur (maybe earlier versions), the app needs Microphone permissions. I haven't figured out how to add permissions for a standalone binary.

https://support.apple.com/en-gb/HT209175

**Comment by rryan** [comment] 2021-02-25 21:10
I'm fighting with the same issue right now trying to use pyaudio. I think what I need to do is get Python to have microphone permissions. I've already gotten my terminal apps added to the list and that hasn't helped.

**Comment by rryan** [comment] 2021-02-25 21:12
Dupe of #514

**Comment by philburk** [comment] 2021-02-27 20:58
Closing because it is a DUP of #514

**Closed by philburk** 2021-02-27 20:58 UTC

**Comment by kunapuli23** [comment] 2021-03-01 18:38
Running into error '-66748' as mentioned above with BigSur, looking forward to release 19.7,  let me know the timeline.
