### ISSUE TITLE
Error -9985 Device Unavailable error for Portaudio Bindings for Python

### ISSUE THREAD

**Issue by rudrathegreat** [PortAudio/portaudio#329] opened 2020-10-14 22:19 UTC
**Describe the bug**
```
Traceback (most recent call last):
  File "D:/Rudra/Python/J.A.R.V.I.S/speech-to-text.py", line 19, in <module>
    input=True)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\testing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable
```

**To Reproduce**
```Python
import pyaudio
import wave

chunk = 1024  # Record in chunks of 1024 samples
sample_format = pyaudio.paInt16  # 16 bits per sample
channels = 2
fs = 44100  # Record at 44100 samples per second
seconds = 3
filename = "output.wav"

p = pyaudio.PyAudio()  # Create an interface to PortAudio

print('Recording')

stream = p.open(format=sample_format,
                channels=channels,
                rate=fs,
                frames_per_buffer=chunk,
                input=True)

frames = []  # Initialize array to store frames

# Store data in chunks for 3 seconds
for i in range(0, int(fs / chunk * seconds)):
    data = stream.read(chunk)
    frames.append(data)

# Stop and close the stream 
stream.stop_stream()
stream.close()
# Terminate the PortAudio interface
p.terminate()

print('Finished recording')

# Save the recorded data as a WAV file
wf = wave.open(filename, 'wb')
wf.setnchannels(channels)
wf.setsampwidth(p.get_sample_size(sample_format))
wf.setframerate(fs)
wf.writeframes(b''.join(frames))
wf.close()
```

**Expected behavior**
I would expect the program to recognise my available microphone, record my voice and then save it.

**Actual behavior**
Error described above

**Desktop (please complete the following information):**
 - OS: Windows x64
 - OS Version 7

**Additional context**

**Comment by RossBencina** [comment] 2020-10-14 23:43
Most likely you have not enabled microphone access for your application in Windows security settings/application permissions. The other possibility is that some other program has the microphone device open.

**Comment by RossBencina** [comment] 2020-10-14 23:44
Closing as not a bug. Also, we're not responsible for the Python bindings.

**Closed by RossBencina** 2020-10-14 23:44 UTC

**Comment by rudrathegreat** [comment] 2020-10-15 07:35
>Most likely you have not enabled microphone access for your application in Windows security settings/application permissions. The other possibility is that some other program has the microphone device open.

Thanks for your instant reply @RossBencina. The reasons described in your message (highlighted above this paragraph) are the most logical reason. I've tried to make sure that other applications that might be using my mic are closed, but error is still being raised. I haven't tried the security option yet, will let you know how that goes.

> Closing as not a bug. Also, we're not responsible for the Python bindings.

Thanks @RossBencina! Regarding the message I highlighted above, is there any platform where I can post this issue since you are not managing the python bindings?

**Comment by rudrathegreat** [comment] 2020-10-15 09:17
Hi @RossBencina i fixed the problem, just a setting thing I had to change! Thanks for the tip!

**Comment by paulmenzel** [comment] 2021-03-12 06:35
@rudrathegreat, for others experiencing this issue, could you please elaborate, what you had to do?

**Comment by rudrathegreat** [comment] 2021-03-12 07:27
Hi @paulmenzel,

I'm using a windows machine, so this won't work on MacBook or Linux.

I went to my input device settings, I selected my mic and went into its properties. After that, I checked the advanced tab of my mic properties and deselected the two checkboxes (I believe the first checkbox is called 'allow applications to take exclusive control of this mic')

Hope that helps.

@sekhrirudra
